version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: make release VERSION=$(date "+%Y%m%d%M%S")
      - persist_to_workspace:
          root: .
          paths:
            - build

  test:
    docker:
      - image: circleci/golang:1.12
    steps:
      - run: go test ./kmers

  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: .
      - run:
          command: |
            VERSION=$( ./build/strangerseq-linux -version )
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./build/

workflows:
  version: 2
  main:
    jobs:
      - build
      - test
      - publish-github-release:
          requires:
            - build
            - test
          filters:
            branches:
              only: master
