version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: make VERSION=${CIRCLE_TAG}
      - persist_to_workspace:
          root: .
          paths:
            - workdir

  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: .
      - run:
        name: "Publish release on github"
        command: |
            VERSION=$(./workdir/strangerseq -version)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./workdir/

workflows:
  version: 2.1
  main:
    jobs:
      - build
      - publish-github-release:
          requires:
            - build
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
